<h1>Bank Marketing Dataset -Preprocessing</h1>

Focuses on cleaning and preprocessing of Dataset

<h2>1.Importing Essential Libraries</h2>

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.preprocessing import StandardScaler 
import warnings 
warnings.filterwarnings("ignore")
print("Libraries Loaded")

Libraries Loaded

<h2>2.Loading Dataset</h2>
Loading the dataset is loaded using pandas.
we also check the shape and preview the first few rows to understand the structure of the data.

In [3]:
df=pd.read_csv("bank-full.csv",sep=";")
print("Shape: ", df.shape)
df.head()

Shape:  (45211, 17)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

<h2>3.Basic Data Understanding</h2>
<p><bold><h5>(a) info()</h5></bold></p>
<p>-info() -> provides column types and missing values</p>
<p>This step helps in identifying:<p>
<p>- Data types</p>
<p>-Missing values</p>
<p>-Distribution of numerical features</p>

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

<p><h5>(b)Describe</h5></p>
<p>function provides a quick statistical overview</p>
<p>It Includes: </p>
<p>- Count -> Number of non-null values</p>
<p>- mean  -> Average vaue</p>
<p>- Standard Deviation -> Measure of dataspread </p>
<p> - Minimum -> smallest value</p>
<p>- 25%, 50%, 75%(Quarties) ->Distribution of data</p>
<p> Maximin -> Largest value</p>

In [5]:
df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

<h2>4. Exploring Categorical Features</h2>
<p>We analyse categorical columns to understand:</p>
<p>- Unique values</p>
<p>- possible inconsistencies</p>
<p>- presence of 'unkown' values</p>

In [6]:
for col in df.select_dtypes(include="object").columns:
    print(f"\n{col}:") 
    print(df[col].value_counts())

job:
job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

marital:
marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64

education:
education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

default:
default
no     44396
yes      815
Name: count, dtype: int64

housing:
housing
yes    25130
no     20081
Name: count, dtype: int64

loan:
loan
no     37967
yes     7244
Name: count, dtype: int64

contact:
contact
cellular     29285
unknown      13020
telephone     2906
Name: count, dtype: int64

month:
month
may    13766
jul     6895
aug     6247
jun     5341
nov     3970
apr     2932
feb     2649
jan     1403
oct      738
sep      579
mar      477
dec      214
Name: count, dtype: int64

poutcome:
poutcome
unknown    36959
failure     4901
other       1840
success     1511
Name: count, dtype: int64

y:
y
no     39922
yes     5289
Name: count, dtype: int64

<h2>5. Checking Duplicates & Missing Values</h2>
<p>We check:</p>
<p>- Duplicate rows</p>
<p>- Null values</p>

In [7]:
print("Duplicate rows:",df.duplicated().sum())
print("\nNull values:") 
print(df.isnull().sum())

Duplicate rows: 0

Null values:
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

<h2>6.Feature Engineering</h2>
<p>A new feature was_previously_contacted</p>
<p>- value = 1 ->Customer was contacted before</p>
<p>- value = 0 -> Customer was not contacted</p>
<p> This improves interpretability and model performance</p>

In [8]:
df['was_previously_contacted']=(df['pdays'] !=-1).astype(int)
print('previously contacted:',df['was_previously_contacted'].value_counts().to_dict())

df['pdays'] = df['pdays'].replace(-1,0)
print('pdays negative values after fix:',(df['pdays'] < 0).sum())

previously contacted: {0: 36954, 1: 8257}
pdays negative values after fix: 0

<h2>7.Handling Data Issues</h2>
<p> Identifying Data Issues</p>
<p> We check for:</p>
<p>- Negative values in balance</p>
<p>-Unusual or inconsitent entries</p>
<p> Understanding such anomalies helps in better preprocessing decisions.</p>

In [9]:
neg_balance= (df['balance'] < 0).sum()
print(f'Negative balance rows: {neg_balance} -> keeping as-is (overdrawn accounts are real)')

Negative balance rows: 3766 -> keeping as-is (overdrawn accounts are real)

<h2>8.Handling 'unknown' values</h2>
<p> Categorical columns may contain 'unknown' values.</p>
<p> These are handled by:</p>
<p> - Replacing with mode</p>
<p> - Ensuring data consistency</p>
<p> This prevents loss of useful data.</p>

In [10]:
cat_cols = df.select_dtypes(include=['object','category']).columns
for col in cat_cols:
    unk = (df[col] == 'unknown').sum()
    if unk > 0:
        pct = round( unk/ len(df) * 100,1)
        print(f'{col:12s}: {unk:5d} unknowns ({pct}%)')

job         :   288 unknowns (0.6%)
education   :  1857 unknowns (4.1%)
contact     : 13020 unknowns (28.8%)
poutcome    : 36959 unknowns (81.7%)

<h2>9.Data Cleaning </h2>
<p> For columns like 'job' ,'unknown' values are replaced using mode.</p>
<p> Helps in maintain realistic data distribution</p>

In [11]:
job_mode = df[df['job'] != 'unknown']['job'].mode()[0]
df['job'] = df['job'].replace('unknown', job_mode)
print(f'job mode used: {job_mode}  | remaining unknowns: {(df["job"]=="unknown").sum()}')

edu_mode = df[df['education'] != 'unknown']['education'].mode()[0]
df['education'] = df['education'].replace('unknown', edu_mode)
print(f'education mode used: {edu_mode}  | remaining unknowns: {(df["education"]=="unknown").sum()}')

print('contact & poutcome unknowns kept as a valid category.')

job mode used: blue-collar  | remaining unknowns: 0
education mode used: secondary  | remaining unknowns: 0
contact & poutcome unknowns kept as a valid category.

<h2>10.Outlier Treatment(IQR Method)</h2>
<p>Outliers are handled using the IQR (InterQuartile Range) method:</p>
<p>-values outside [Q1 - 1.5*IQR, Q3 + 1.5*IQR] are capped</p>
<p>Thi prevents extreme vales from skewing the model.</p>

In [12]:
def cap_iqr(df,col):
    Q1, Q3= df[col].quantile(0.25), df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower, upper = Q1 - 1.5*IQR, Q3 + 1.5*IQR
    n= df[(df[col]<lower) | (df[col] > upper)].shape[0]
    df[col] = df[col].clip(lower,upper)
    print(f" {col:12s} [{lower:8.1f},{upper:8.1f}] | {n} capped") 
    return df

print("capping outliers...\n") 
for col in ["age","balance","duration" ,"campaign"]:
    df = cap_iqr(df, col)

capping outliers...

 age          [    10.5,    70.5] | 487 capped
 balance      [ -1962.0,  3462.0] | 4729 capped
 duration     [  -221.0,   643.0] | 3235 capped
 campaign     [    -2.0,     6.0] | 3064 capped

<h2>11.Final Cleaning of 'unknown'</h2>
<p> Final Cleaning of remainng 'unknown' values</p>
<p>A Final pass is done to ensure no 'unknown' values remain in categorical Clean data = Better model performance</p>

In [13]:
for col in df.select_dtypes(include="object").columns:
    u = (df[col] =="unknown").sum()
    if u>0:
        print( f" {col:12s}:  {u} ({u/len(df)*100:.1f}%)")

 contact     :  13020 (28.8%)
 poutcome    :  36959 (81.7%)

<h2>12.Encoding Month Column</h2>
<p> Encoding Month Feature </p>
<p>The 'month' column is converted into numerical foramt:</p>
<p>Example: </p>
<p>-jan -> 1</p>
<p>-Feb -> 2</p>
<p> This makes it usable for machine learning algorithms</p>

In [14]:
month_order = {'jan':1 ,'feb':2 ,'mar':3 ,'apr':4,'may':5,'jun':6,
               'jul':7 ,'aug':8 , 'sep':9,'oct':10, 'nov':11,'dec':12}
df['month_num'] = df['month'].map(month_order)

df['age_group']= pd.cut(df['age'],
                        bins=[17,29,39,49,59,100],
                        labels=['18-29','30-39','40-49','50-59','60+'])

df['balance_tier']= pd.cut(df['balance'],
                           bins=[-np.inf,0,500,2000,np.inf],
                           labels=['Negative','Low','Medium','High'])

print('New features added: month_num , age_group, balance_tier, was_previously_contacted')
print(df[['age_group','balance_tier','month_num', 'was_previously_contacted']].head())

New features added: month_num , age_group, balance_tier, was_previously_contacted
  age_group balance_tier  month_num  was_previously_contacted
0     50-59         High          5                         0
1     40-49          Low          5                         0
2     30-39          Low          5                         0
3     40-49       Medium          5                         0
4     30-39          Low          5                         0

<h2>13.Saving Preprocessed Data</h2>
<p> The final preprocessed dataset is saved as:</p>
<p>'final_preprocessed.csv'</p>
<p>This dataset is now ready for:</p>
<p>- Visualization</p>
<p>- Model training</p>
<p>- Evaluation</p>

In [15]:
df.to_csv('final_preprocessed.csv',index=False)
print(f'saved: final_preprocessed.csv | shape: {df.shape}')
print('\n Final column list:') 
print(df.columns.tolist())

saved: final_preprocessed.csv | shape: (45211, 21)

 Final column list:
['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y', 'was_previously_contacted', 'month_num', 'age_group', 'balance_tier']